spring:
  application:
    name: apollo-configservice-fat
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171

server:
  port: 9001

logging:
  file: /opt/logs/100003171/apollo-configservice.log
